### ISSUE TITLE
Disable support for @psalm-var, param,return,property,property-read,property-write tags

### ISSUE THREAD

**Issue by MaXal** [JetBrains/phpstorm-psalm-plugin#57]
According to the [specification](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-var-psalm-param-psalm-return-psalm-property-psalm-property-read-psalm-property-write): 

_When specifying types in a format not supported by phpDocumentor (but supported by Psalm) you may wish to prepend @psalm- to the PHPDoc tag, so as to avoid confusing your IDE. If a @psalm-prefixed tag is given, Psalm will use it in place of its non-prefixed counterpart._

Processing them PhpStorm produce a lot of warning which are impossible to workaround.

**Comment by wbars** [comment]
Fixed in different way: since original reason why IDE highlights such references is that it doesn't understand where these reference are resolved, then trying to resolve this to remove highlighting both for `@psalm-` tags and common ones.

Now IDE will treat types that are reference from on of the following places:
- `@template`
- `@psalm-type`
- `@psalm-imported-types`
As generally MIXED and won't highlight them as undefined for any tags, not only for `@psalm-` ones. This is partially workaround before full support for such tags, after that fix current solution may be reconsidered.

**Comment by orklah** [comment]
I'd love to have an inspection to suggest moving @psalm- annotation directly into @param/@return/@var when the annotation can be understood by IDE.

That way, the IDE can continue considering @psalm- as unknown while still suggesting migrating every supported syntax into common annotation that will then be parsed.

**Comment by MaXal** [comment]
@orklah That is a great idea! I've created a feature request that will cover this: #61
